<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
abstract class PluginsfSympalContentType extends BasesfSympalContentType
{
  protected $_routeObject;

  public function __toString()
  {
    return (string) $this->getLabel();
  }

  public function getRouteName()
  {
    return '@'.str_replace('-', '_', $this->getSlug());
  }

  public function getRoutePath()
  {
    $path = $this->default_path;
    if ($path != '/')
    {
      $path .= '.:sf_format';
    }
    return $path;
  }

  public function getRouteObject()
  {
    if (!$this->_routeObject)
    {
      $this->_routeObject = new sfRoute($this->getRoutePath(), array(
        'sf_format' => 'html',
        'sf_culture' => sfConfig::get('default_culture')
      ));
    }
    return $this->_routeObject;
  }

  /**
   * Returns the module name this content type record should be rendered with
   *
   * Used when building the route for this content type
   *
   * @return string
   */
  public function getModuleToRenderWith()
  {
    if ($moduleName = $this->_get('module'))
    {
      return $moduleName;
    }
    else
    {
      return sfSympalConfig::getDeep('content_types', $this['name'], 'default_rendering_module', sfSympalConfig::get('default_rendering_module', null, 'sympal_content_renderer'));
    }
  }

  /**
   * Returns the action name this content type record should be rendered with
   *
   * Used when building the route for this content type
   *
   * @return string
   */
  public function getActionToRenderWith()
  {
    if ($actionName = $this->_get('action'))
    {
      return $actionName;
    }
    else
    {
      return sfSympalConfig::getDeep('content_types', $this['name'], 'default_rendering_action', sfSympalConfig::get('default_rendering_action', null, 'index'));
    }
  }
}