all:
  sympal_config:

    # the class used for the extended actions class
    extended_actions_class:  sfSympalActions

    # Configure internationalization
    i18n: false

    # Configure the default culture
    default_culture: en

    # Configure the available languages
    language_codes: []
    
    # used for outputting date published slot. See sfDateFormat::getPattern()
    # http://trac.symfony-project.org/browser/branches/1.4/lib/i18n/sfDateFormat.class.php
    date_published_format: D

    # Configure the default rendering module and action
    default_rendering_module: sympal_content_renderer
    default_rendering_action: index

    # Configure what to do when you access some content that is not published yet
    unpublished_content:
      forward_to: [sympal_default, unpublished_content]
      forward_404: false

    internationalized_models:
      sfSympalSite: [page_title, meta_keywords, meta_description]
      sfSympalContent: [i18n_slug, page_title, meta_keywords, meta_description]

    # Configure the available formats to render content in
    content_formats:
      - html
      - atom
      - feed
      - atom1
      - rss
      - rss10
      - rss091
      - rss201
      - xml
      - yml
      - json
