<?php echo sfSympalContentToolkit::getContentRoutesYaml() ?>

<?php echo sfSympalContentToolkit::getRedirectRoutesYaml() ?>

homepage:
  url:   /
  param: { module: <?php echo sfSympalConfig::get('default_rendering_module', null, 'sympal_content_renderer') ?>, action: <?php echo sfSympalConfig::get('default_rendering_action', null, 'action') ?>, result_type: object, sympal_content_type: sfSympalPage, sympal_content_slug: home }
  class: sfDoctrineRoute
  options:
    allow_empty: true
    model:  sfSympalContent
    type:   object
    method: getContent

sympal_change_language_form:
  url:   /change_language
  param: { module: sympal_default, action: change_language }
  requirements:
    sf_method: [post]

sympal_change_language:
  url:   /change_language/:language
  param: { module: sympal_default, action: change_language }

sympal_change_edit_language:
  url:   /change_edit_language/:language
  param: { module: sympal_default, action: change_edit_language }
