# default homepage route. This will be overwritten if either:
#  a) A homepage route is in the application's routing.yml
# OR
#  b) A route has a custom_path of "/"
homepage:
  url:   /
  param: { module: sympal_default, action: new_site }

<?php echo sfSympalToolkit::getContentRoutesYaml() ?>

sympal_change_language_form:
  url:   /change_language
  param: { module: sympal_default, action: change_language }
  requirements:
    sf_method: [post]

sympal_change_language:
  url:   /change_language/:language
  param: { module: sympal_default, action: change_language }

sympal_change_edit_language:
  url:   /change_edit_language/:language
  param: { module: sympal_default, action: change_edit_language }


# Admin-generated content-related modules
sympal_content_types:
  class:                  sfDoctrineRouteCollection
  options:
    model:                sfSympalContentType
    module:               sympal_content_types
    prefix_path:          admin/content/types
    with_wildcard_routes: true
