# default homepage route. This will be overwritten if either:
#  a) A homepage route is in the application's routing.yml
# OR
#  b) A route has a custom_path of "/"
homepage:
  url:   /
  param: { module: sympal_default, action: new_site }

<?php echo sfSympalToolkit::getContentRoutesYaml() ?>

# The absolute default route for a content record if everything else falls through
sympal_content_view:
  url: /content/:slug
  param: { module: <?php echo sfSympalConfig::get('default_rendering_module', null, 'sympal_content_renderer') ?>, action: <?php echo sfSympalConfig::get('default_rendering_action', null, 'index') ?>, result_type: object }
  class: sfDoctrineRoute
  options:
    model:  sfSympalContent
    type:   object
    method: getContent

sympal_change_language_form:
  url:   /change_language
  param: { module: sympal_default, action: change_language }
  requirements:
    sf_method: [post]

sympal_change_language:
  url:   /change_language/:language
  param: { module: sympal_default, action: change_language }

sympal_change_edit_language:
  url:   /change_edit_language/:language
  param: { module: sympal_default, action: change_edit_language }


# Admin-generated content-related modules
sympal_content_types:
  class:                  sfDoctrineRouteCollection
  options:
    model:                sfSympalContentType
    module:               sympal_content_types
    prefix_path:          admin/content/types
    with_wildcard_routes: true

sympal_sites:
  class:                  sfDoctrineRouteCollection
  options:
    model:                sfSympalSite
    module:               sympal_sites
    prefix_path:          admin/sites
    with_wildcard_routes: true

# The slightly more complex content admin module
sympal_content:
  class:                  sfDoctrineRouteCollection
  options:
    model:                sfSympalContent
    module:               sympal_content
    prefix_path:          admin/content/manage
    with_wildcard_routes: true

# Displays a list of the content types, like an index page for all content
sympal_content_types_index:
  url:  /admin/content
  param: { module: sympal_content, action: content_types_index }

# Displays and allows for editing of a content record's slot
sympal_content_edit_slots:
  url:  /admin/content/:id/edit_slots
  param: { module: sympal_content, action: edit_slots }

sympal_content_create_type:
  url:    /admin/content/manage/create/:type
  param:  { module: sympal_content, action: create_type }

sympal_content_list_type:
  url:    /admin/content/manage/type/:type
  param: { module: sympal_content, action: list_type }