sfSympalSite:
  actAs:
    sfSympalRecordTemplate:
    Sluggable:
      fields: [title]
      indexName: site_sluggable
  columns:
    theme: string(255)
    title:
      type: string(255)
      notnull: true
    description:
      type: clob
      notnull: false
    page_title: string(255)
    meta_keywords: string(500)
    meta_description: string(500)

sfSympalContent:
  actAs:
    Timestampable:
    sfSympalRecordTemplate:
    sfSympalContentModelTemplate:
    sfInlineObjectContainerTemplate:
      relations:    [Assets, Links]
    Sluggable:
      builder:      [sfSympalContent, slugBuilder]
  columns:
    site_id:
      type: integer
      notnull: true
    content_type_id:
      type: integer
      notnull: true
    last_updated_by_id: integer
    created_by_id: integer
    date_published: timestamp
    custom_path: string(255)
    theme: string(255)
    template: string(255)
    module: string(255)
    action: string(255)
    publicly_editable:
      type: boolean
      default: false
    page_title: string(255)
    meta_keywords: string(500)
    meta_description: string(500)
    i18n_slug: string(255)
  indexes:
    date_published:
      fields: [date_published]
  relations:
    LastUpdatedBy:
      class: <?php echo sfSympalConfig::get('user_model') ?> 
      local: last_updated_by_id
      foreignAlias: LastUpdatedContent
      onDelete: SET NULL
    CreatedBy:
      class: <?php echo sfSympalConfig::get('user_model') ?> 
      local: created_by_id
      foreignAlias: CreatedContent
      onDelete: SET NULL
    Site:
      local: site_id
      class: sfSympalSite
      onDelete: CASCADE
      foreignAlias: Content
    Type:
      local: content_type_id
      class: sfSympalContentType
      onDelete: CASCADE
      foreignAlias: Content
    Groups:
      class: <?php echo sfSympalConfig::get('group_model') ?> 
      local: content_id
      foreign: group_id
      refClass: sfSympalContentGroup
      foreignAlias: Content
    EditGroups:
      class: <?php echo sfSympalConfig::get('group_model') ?> 
      local: content_id
      foreign: group_id
      refClass: sfSympalContentEditGroup
      foreignAlias: EditContent
    Slots:
      class: sfSympalContentSlot
      refClass: sfSympalContentSlotRef
      local: content_id
      foreign: content_slot_id
      foreignAlias: Content
    Links:
      class: sfSympalContent
      refClass: sfSympalContentLink
      local: content_id
      foreign: linked_content_id
      autoComplete: false

sfSympalContentType:
  actAs:
    sfSympalRecordTemplate:
    Sluggable:
      fields:    [label]
      indexName: content_type_sluggable
  columns:
    # The name of the model to use as the data source (e.g. sfSympalPage).
    # Must act as sfSympalContentTypeTemplate
    name:
      type: string(255)
      notnull: true
    description: clob
    label:
      type: string(255)
      notnull: true
    default_path: string(255)
    theme: string(255)
    template: string(255)
    module: string(255)
    action: string(255)
  indexes:
    content_type_name:
      fields: [name]

sfSympalContentGroup:
  actAs: [sfSympalRecordTemplate]
  options:
    symfony:
      form: false
      filter: false
  columns:
    content_id:
      primary: true
      type: integer
    group_id:
      primary: true
      type: integer
  relations:
    Content:
      local: content_id
      class: sfSympalContent
      foreignAlias: ContentGroups
      onDelete: CASCADE
    Group:
      class: <?php echo sfSympalConfig::get('group_model') ?> 
      local: group_id
      foreignAlias: ContentGroups
      onDelete: CASCADE

sfSympalContentEditGroup:
  actAs: [sfSympalRecordTemplate]
  options:
    symfony:
      form: false
      filter: false
  columns:
    content_id:
      primary: true
      type: integer
    group_id:
      primary: true
      type: integer
  relations:
    Content:
      local: content_id
      class: sfSympalContent
      foreignAlias: ContentEditGroups
      onDelete: CASCADE
    Group:
      class: <?php echo sfSympalConfig::get('group_model') ?> 
      local: group_id
      foreignAlias: ContentEditGroups
      onDelete: CASCADE