sfSympalSite:
  actAs:
    sfSympalRecordTemplate:
    Sluggable:
      fields: [name]
      indexName: site_sluggable
  columns:
    name:                   # A common identifier for the site
      type:    string(255)
      notnull: true
    slug:                   # The key for this site - corresponds with sfSympalConfig::getCurrentSiteName()
      type:    string(255)
      notnull: true
    description:
      type:    clob
      notnull: false
    page_title:       string(255)
    meta_keywords:    string(500)
    meta_description: string(500)

sfSympalContent:
  actAs:
    Timestampable:
    sfSympalRecordTemplate:
  columns:
    site_id:
      type:    integer
      notnull: true
    content_type_id:
      type:    integer
      notnull: true
    slug:
      type:    string(255)
      notnull: true
    date_published:     timestamp
    custom_path:        string(255)
    rendering_method:   string(255)
    page_title:         string(255)
    meta_keywords:      string(500)
    meta_description:   string(500)
    i18n_slug:          string(255)
    last_updated_by_id: integer
    created_by_id:      integer
  indexes:
    date_published:
      fields: [date_published]
  relations:
    Site:
      local:        site_id
      class:        sfSympalSite
      onDelete:     CASCADE
      foreignAlias: Content
    Type:
      local:        content_type_id
      class:        sfSympalContentType
      onDelete:     CASCADE
      foreignAlias: Content
    LastUpdatedBy:
      class:        sfGuardUser
      local:        last_updated_by_id
      foreignAlias: LastUpdatedContent
      onDelete:     SET NULL
    CreatedBy:
      class:        sfGuardUser
      local:        created_by_id
      foreignAlias: CreatedContent
      onDelete:     SET NULL

sfSympalContentType:
  actAs:
    sfSympalRecordTemplate:
  columns:
    # The the key corresponding to the app.yml entry
    key:
      type: string(255)
      notnull: true
    default_path: string(255)
  indexes:
    content_type_key:
      fields: [key]
