sfSympalSite:
  actAs:
    sfSympalRecordTemplate:
    Sluggable:
      fields: [name]
      indexName: site_sluggable
  columns:
    name:                   # A common indentifier for the site
      type:    string(255)
      notnull: true
    slug:                   # The key for this site - corresponds with sfSympalConfig::getCurrentSiteName()
      type:    string(255)
      notnull: true
    description:
      type:    clob
      notnull: false
    page_title:       string(255)
    meta_keywords:    string(500)
    meta_description: string(500)

sfSympalContent:
  actAs:
    Timestampable:
    sfSympalRecordTemplate:
    sfSympalContentModelTemplate:
    Sluggable:
      builder:      [sfSympalContent, slugBuilder]
      uniqueBy:     [content_type_id]      
  columns:
    site_id:
      type:    integer
      notnull: true
    content_type_id:
      type:    integer
      notnull: true
    slug:
      type:    string(255)
      notnull: true
    last_updated_by_id: integer
    created_by_id:      integer
    date_published:     timestamp
    custom_path:        string(255)
    template:           string(255)
    module:             string(255)
    action:             string(255)
    page_title:         string(255)
    meta_keywords:      string(500)
    meta_description:   string(500)
    i18n_slug:          string(255)
  indexes:
    date_published:
      fields: [date_published]
  relations:
    LastUpdatedBy:
      class:        sfGuardUser
      local:        last_updated_by_id
      foreignAlias: LastUpdatedContent
      onDelete:     SET NULL
    CreatedBy:
      class:        sfGuardUser
      local:        created_by_id
      foreignAlias: CreatedContent
      onDelete:     SET NULL
    Site:
      local:        site_id
      class:        sfSympalSite
      onDelete:     CASCADE
      foreignAlias: Content
    Type:
      local:        content_type_id
      class:        sfSympalContentType
      onDelete:     CASCADE
      foreignAlias: Content

sfSympalContentType:
  actAs:
    sfSympalRecordTemplate:
    Sluggable:
      fields:    [label]
      indexName: content_type_sluggable
  columns:
    # The name of the model to use as the data source (e.g. sfSympalPage).
    # Must act as sfSympalContentTypeTemplate
    name:
      type: string(255)
      notnull: true
    description: clob
    label:
      type: string(255)
      notnull: true
    default_path: string(255)
    template: string(255)
    module: string(255)
    action: string(255)
  indexes:
    content_type_name:
      fields: [name]
